version: '3.8'


services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload