name: Run Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # горе 
      - name: Merge to main
        if: success() 
        run: |
          git checkout main || git checkout -b main
          git rm -r .github/
          git rm -r back/
          git rm .gitignore
          git commit -m "Удаляем лишние файлы"
          git push origin main
      # конец горя 